### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by filviu** [jcppkkk/OpenWithSublime#1]
Hi,

I started shamelessly forking your work to create a simillar set of scripts for VSCode than realized that the license of this code is not specified. 

Would it be ok to go ahead?

**Comment by cometjc** [comment]
Hi silviuvulcan, 
 It's origin from my gist https://gist.github.com/jcppkkk/8330314
Which is a fork of a fork of https://gist.github.com/mrchief/5628677

You can ask him for licence detail, and also let me know if you have progress :)
